---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: catalog-catalog-apiserver
  name: catalog-catalog-apiserver
spec:
  ports:
  - name: secure
    nodePort: 30443
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: catalog-catalog-apiserver
  type: NodePort
