---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: catalog-catalog
  name: catalog-catalog-controller-manager
spec:
  minReadySeconds: 1
  replicas: 1
  selector:
    matchLabels:
      app: catalog-catalog-controller-manager
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "false"
      labels:
        app: catalog-catalog-controller-manager
    spec:
      containers:
      - args:
        - controller-manager
        - --secure-port
        - "8444"
        - --cluster-id-configmap-namespace=default
        - --leader-elect=false
        - -v
        - "10"
        - --resync-interval
        - 5m
        - --broker-relist-interval
        - 24h
        - --operation-polling-maximum-backoff-duration
        - 20m
        - --feature-gates
        - OriginatingIdentity=true
        - --feature-gates
        - ServicePlanDefaults=false
        env:
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/kubernetes-service-catalog/service-catalog:v0.2.1
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8444
            scheme: HTTPS
          initialDelaySeconds: 40
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: controller-manager
        ports:
        - containerPort: 8444
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /healthz/ready
            port: 8444
            scheme: HTTPS
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /var/run/kubernetes-service-catalog
          name: service-catalog-cert
          readOnly: true
      serviceAccountName: service-catalog-controller-manager
      volumes:
      - name: service-catalog-cert
        secret:
          items:
          - key: tls.crt
            path: apiserver.crt
          - key: tls.key
            path: apiserver.key
          secretName: catalog-catalog-apiserver-cert
