---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: servicecatalog.k8s.io:cluster-info-configmap
  namespace: default
rules:
- apiGroups:
  - ""
  resourceNames:
  - cluster-info
  resources:
  - configmaps
  verbs:
  - get
  - create
  - list
  - watch
  - update
