---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-catalog-controller-manager-leader-election
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: servicecatalog.k8s.io:leader-locking-controller-manager
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: service-catalog-controller-manager
  namespace: default
